# Generated by Django 4.1.1 on 2022-11-17 08:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Model_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, verbose_name='Field Type')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Model Field',
                'verbose_name_plural': 'Model Fields',
            },
        ),
        migrations.CreateModel(
            name='DJ_Relationship_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, verbose_name='Field Type')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Relationship Field',
                'verbose_name_plural': 'Relationship Fields',
            },
        ),
        migrations.CreateModel(
            name='DJ_Model_Field_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Field Attribute')),
                ('value_type', models.CharField(choices=[('', '-- Make A Choice --'), ('str', 'String'), ('int', 'Integer'), ('obj', 'Object'), ('set', 'Set'), ('bol', 'Boolean'), ('lst', 'List')], max_length=3)),
                ('description', tinymce.models.HTMLField()),
                ('fields', models.ManyToManyField(db_table='model_attribute_field_mapping_new_table', null=True, to='DJ_Studio.dj_model_field')),
            ],
            options={
                'verbose_name': 'Model Field Attribute',
                'verbose_name_plural': 'Model Field Attributes',
            },
        ),
    ]
