# Generated by Django 4.1.1 on 2022-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_Studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj_model_field_attribute',
            name='fields',
            field=models.ManyToManyField(db_table='model_attribute_field_mapping_table', null=True, to='DJ_Studio.dj_model_field'),
        ),
    ]
