# Generated by Django 4.1.1 on 2022-11-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, verbose_name='Field Type')),
            ],
        ),
        migrations.CreateModel(
            name='DJField_Atrribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Attribute')),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'integer'), ('obj', 'object'), ('set', 'set')], max_length=3)),
            ],
        ),
    ]
