# Generated by Django 4.1.1 on 2022-11-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djfield',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
