# Generated by Django 4.1.1 on 2022-11-12 13:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0002_djfield_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DJField_Atrribute',
            new_name='DJField_Attribute',
        ),
        migrations.AlterModelOptions(
            name='djfield',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='djfield_attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attribute'},
        ),
        migrations.AddField(
            model_name='djfield',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
