# Generated by Django 4.1.1 on 2022-11-12 13:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0003_rename_djfield_atrribute_djfield_attribute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djfield_attribute',
            options={'verbose_name': 'Field Attribute', 'verbose_name_plural': 'Field Attributes'},
        ),
        migrations.AddField(
            model_name='djfield_attribute',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djfield_attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Field Attribute'),
        ),
        migrations.AlterField(
            model_name='djfield_attribute',
            name='value_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('obj', 'Object'), ('set', 'Set'), ('bol', 'Boolean')], max_length=3),
        ),
    ]
