# Generated by Django 4.1.1 on 2022-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0004_alter_djfield_attribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djfield_attribute',
            name='value_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('obj', 'Object'), ('set', 'Set'), ('bol', 'Boolean')], default='str', max_length=3),
        ),
    ]
