# Generated by Django 4.1.1 on 2022-11-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0005_alter_djfield_attribute_value_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djfield',
            name='desc',
        ),
        migrations.AlterField(
            model_name='djfield_attribute',
            name='value_type',
            field=models.CharField(choices=[('', '-- Make A Choice --'), ('str', 'String'), ('int', 'Integer'), ('obj', 'Object'), ('set', 'Set'), ('bol', 'Boolean'), ('lst', 'List')], max_length=3),
        ),
    ]
