# Generated by Django 4.1.1 on 2022-11-14 15:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0006_remove_djfield_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Relationship_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100, verbose_name='Field Type')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Relationship Field',
                'verbose_name_plural': 'Relationship Fields',
            },
        ),
        migrations.RenameModel(
            old_name='DJField',
            new_name='DJ_Model_Field',
        ),
        migrations.RenameModel(
            old_name='DJField_Attribute',
            new_name='DJ_Model_Field_Attribute',
        ),
        migrations.AlterModelOptions(
            name='dj_model_field',
            options={'verbose_name': 'Model Field', 'verbose_name_plural': 'Model Fields'},
        ),
    ]
