# Generated by Django 4.1.1 on 2022-11-14 16:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0007_dj_relationship_field_rename_djfield_dj_model_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Snippet_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('snippet', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
            },
        ),
    ]
