# Generated by Django 4.1.1 on 2022-11-15 04:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0008_dj_snippet_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', tinymce.models.HTMLField()),
                ('is_Concept_Clear', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
            },
        ),
        migrations.RenameModel(
            old_name='DJ_Snippet_Field',
            new_name='DJ_Snippet',
        ),
    ]
