# Generated by Django 4.1.1 on 2022-11-16 07:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0009_dj_concept_rename_dj_snippet_field_dj_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_Howto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howto', models.CharField(max_length=100, verbose_name='How To')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'How To',
                'verbose_name_plural': 'How-tos',
            },
        ),
        migrations.AlterModelOptions(
            name='dj_concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AlterModelOptions(
            name='dj_model_field_attribute',
            options={'verbose_name': 'Model Field Attribute', 'verbose_name_plural': 'Model Field Attributes'},
        ),
        migrations.AddField(
            model_name='dj_model_field_attribute',
            name='fields',
            field=models.ManyToManyField(db_table='model_attribute_field_mapping_table', null=True, to='dj_knowledge.dj_model_field'),
        ),
        migrations.AlterField(
            model_name='dj_concept',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
