# Generated by Django 4.1.1 on 2022-11-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_knowledge', '0010_dj_howto_alter_dj_concept_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj_model_field_attribute',
            name='fields',
        ),
        migrations.DeleteModel(
            name='DJ_Relationship_Field',
        ),
        migrations.DeleteModel(
            name='DJ_Model_Field',
        ),
        migrations.DeleteModel(
            name='DJ_Model_Field_Attribute',
        ),
    ]
