# Generated by Django 4.1.1 on 2022-11-17 14:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('dj_knowledge', '0011_remove_dj_model_field_attribute_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj_howto',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
